export enum Estado {
  PREPARACION = "PREPARACION",
  PENDIENTE = "PENDIENTE",
  TERMINADO = "TERMINADO",
  EN_DELIVERY = "EN_DELIVERY",
  ENTREGADO = "ENTREGADO",
  FACTURADO = "FACTURADO"
}
